spring.datasource.url=jdbc:postgresql://localhost:5433/pathpulse
spring.datasource.username=admin
spring.datasource.password=kanishk

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'Asia/Kolkata'

spring.data.redis.host=localhost
spring.data.redis.port=6379